name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
        - parallel:
            - name: Checkout SDK & Build Tools
              uses: actions/checkout@v7
              with:
                  repository: AdrianGin/Civ4-SDK
                  path: Civ4SDK
                  fetch-depth: 0                        

            - name: Checkout Source Code
              uses: actions/checkout@v7
              with:
                  path: source
                  fetch-depth: 0

        - name: Download Civ4 SDK & Build Tools
          run: |
              Set-PSDebug -Trace 1
              mkdir C:\Civ4SDK
              mv "Civ4SDK\Microsoft Visual C++ Toolkit 2003" "C:\Civ4SDK"
              mv "Civ4SDK\WindowsSDK" "C:\Civ4SDK"
              cp -r -v -Force "Civ4SDK\CvGameCoreDLL" "$env:GITHUB_WORKSPACE\source\"
          shell: powershell
    
        - parallel:
            

            - name: Compile CvGameCoreDLL
              run: |
                Set-PSDebug -Trace 1
                $env:TOOLKIT="C:\Civ4SDK\Microsoft Visual C++ Toolkit 2003"
                $env:PSDK="C:\Civ4SDK\WindowsSDK"
                $env:CIV4_LIB_INSTALL_PATH="C:\Civ4SDK" 

                # Prepend VC 2003 binary directory to PATH so nmake & cl use VC 2003
                $env:Path = "$env:TOOLKIT\bin;$env:PSDK\bin;$env:Path"
                where.exe cvtres.exe
                cd source/CvGameCoreDLL/Project
                cmake --preset Release
                cmake --build --preset "DLL Release"
              shell: powershell
              
            - name: Compile CvGameCoreDLL (Debug)
              run: |
                Set-PSDebug -Trace 1
                $env:TOOLKIT="C:\Civ4SDK\Microsoft Visual C++ Toolkit 2003"
                $env:PSDK="C:\Civ4SDK\WindowsSDK"
                $env:CIV4_LIB_INSTALL_PATH="C:\Civ4SDK" 

                # Prepend VC 2003 binary directory to PATH so nmake & cl use VC 2003
                $env:Path = "$env:TOOLKIT\bin;$env:PSDK\bin;$env:Path"
                where.exe cvtres.exe
                cd source/CvGameCoreDLL/Project
                cmake --preset Debug
                cmake --build --preset "DLL Debug"
              shell: powershell              

            
        - name: Upload DLL
          uses: actions/upload-artifact@v7
          with:
            name: CvGameCoreDLL
            path: source/CvGameCoreDLL/Project/Release/CvGameCoreDLL.dll           